Tammy/add fm pileup aggregation
Ultimagen/ugbio-utils pull request #55
Opened 2024-11-10 12:41 UTC by TammushB

2024-11-11 07:13 UTC, ilyasoifer reviewed
I think it is OK to write it this way, the only preference is that the filtering (applying xgboost) and aggregation of the pileup should be separated.

2024-11-18 09:06 UTC, GatKrieger requested changes

2024-11-24 19:45 UTC, TammushB commented on src/featuremap/ugbio_featuremap/featuremap_xgb_prediction.py
> +added_agg_features = {
converted to 2 dicts

2024-11-28 10:48 UTC, GatKrieger commented on src/featuremap/ugbio_featuremap/featuremap_xgb_training.py
> +def split_data_every_2nd_variant(X, y):  # noqa: N802, N803
Or, I guess it's better to define minimal/maximal number of variants to train on?

2024-12-02 08:23 UTC, TammushB commented on src/featuremap/ugbio_featuremap/featuremap_xgb_prediction.py
> +    if "is_cycle_skip" in record_info_dict:
sorry can't take this without the 'if' statement. 
is_cycle_skip is not always present in the record_info_dict. 
So I need the if to add it if not present.

2024-12-02 08:53 UTC, TammushB commented on src/featuremap/ugbio_featuremap/featuremap_xgb_training.py
> +def split_data_every_2nd_variant(X, y):  # noqa: N802, N803
added another split option

2024-12-02 13:15 UTC, GatKrieger approved these changes
I approve but I also ask for some changes.
@ilyasoifer please review the training part. I've read it but I'm not an expert (yet!)

2024-12-02 13:15 UTC, GatKrieger commented on src/featuremap/ugbio_featuremap/featuremap_xgb_prediction.py
> +ppm_added_agg_features = {}
also here..

2024-12-02 13:15 UTC, GatKrieger commented on src/featuremap/ugbio_featuremap/featuremap_xgb_prediction.py
> +    if "is_cycle_skip" in record_info_dict:
but the .get method deals with these cases. This is also what I did in: /home/ubuntu/ugbio-utils/src/featuremap/ugbio_featuremap/featuremap_consensus_utils.py line: 312

2024-12-02 13:15 UTC, GatKrieger commented on src/featuremap/ugbio_featuremap/featuremap_xgb_training.py
> +def split_data_every_2nd_variant(X, y):  # noqa: N802, N803
So I guess there's no need in this function, right? this is just a specific case: split_data(X, y, test_size=0.5, random_state=42)

2024-12-03 09:47 UTC, ilyasoifer approved these changes
Looks good, just minor things

2024-12-03 09:54 UTC, TammushB commented on src/featuremap/ugbio_featuremap/featuremap_xgb_training.py
> +    XGBoost_evaluate_model(xgb_clf_es, y_test, y_pred_es)
not sure I understand. 
the results of this analysis are outputted to the log alongside with the cross_validation results. 
altogether they suppose to suggest if there is actual overfitting.

2024-12-03 10:20 UTC, TammushB commented on src/featuremap/ugbio_featuremap/featuremap_xgb_training.py
> +    XGBoost_evaluate_model(xgb_clf_es, y_test, y_pred_es)
Ahh got it! adding it.

2024-12-03 10:50 UTC, merged