BIOIN-1909-ugbio-cnv-docker-missing-tabix
Ultimagen/ugbio-utils pull request #65
Opened 2024-11-18 11:47 UTC by TammushB

replace tabix with bcftools

2024-11-18 16:56 UTC, TammushB commented
@avigailmo  instead of installing tabix , I choose to use bcftools (already installed) to index the vcf.

2024-11-19 05:30 UTC, avigailmo requested changes
please add check that vcf index created in the test

2024-11-19 05:30 UTC, avigailmo commented on src/cnv/ugbio_cnv/convert_cnv_results_to_vcf.py
> +        except subprocess.CalledProcessError as e:
👍

2024-11-19 05:30 UTC, avigailmo commented on src/cnv/tests/system/test_convert_cnv_results_to_vcf.py
> +        out_vcf_file = pjoin(tmp_path, sample_name + ".cnv.vcf.gz")
can you add verification of the vcf index creation?

2024-11-19 08:29 UTC, merged