Bioin 1965 ugbio filtering
Ultimagen/ugbio-utils pull request #80
Opened 2024-12-26 10:13 UTC by avigailmo

2025-01-21 21:19 UTC, ilyasoifer commented
@avigailmo - I think this is back to you. Tests pass now. I am not sure I did not break anything in the pyproject.toml and, of course, did not take care of removing the code from VariantCalling. 

Have fun

2025-02-05 09:45 UTC, inbalzelig-ugi requested changes

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/comparison/tests/unit/test_vcf_pipeline_utils.py
> +    data = read_hdf(pjoin(resources_dir, "h5_file_unitest.h5"), key="concordance")
```suggestion
    data = read_hdf(resources_dir / "h5_file_unitest.h5", key="concordance")
```

In general, we prefer Path rather than pjoin (when possible)

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/comparison/ugbio_comparison/vcf_pipeline_utils.py
> +def _fix_errors(df: pd.DataFrame) -> pd.DataFrame:
```suggestion
def fix_errors(df: pd.DataFrame) -> pd.DataFrame:
```

Even consider a moer descriptive name for this function

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/comparison/ugbio_comparison/vcf_pipeline_utils.py
> +from __future__ import annotations
remove

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/comparison/ugbio_comparison/vcf_pipeline_utils.py
> +class VcfPipelineUtils:
move this class to a separate file. Do the same for the test file. It will make the code much more readable

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/core/ugbio_core/concordance/concordance_utils.py
> +from __future__ import annotations
remove

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/filtering/Dockerfile
> +    git \
see the comment on the comparison dockerfile

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/filtering/Dockerfile
why not take the comparison docker image as the base instead of ugbio_base? I see the only difference is that you add the ugbio filtering package

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/filtering/README.filtering.md
> +This module includes filtering python scripts and utils for bioinformatics pipelines.
Filtering of what?

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/filtering/pyproject.toml
> +    "xgboost==2.1.2",
is it necessary to use one specific xgboost version? It can cause problems if other members use xgboost of different versions.

2025-02-05 09:45 UTC, inbalzelig-ugi commented on src/filtering/ugbio_filtering/sec/allele_counter.py
what is this "sec" folder? is it a name of a tool?

2025-02-05 10:23 UTC, avigailmo commented on .devcontainer/filtering/devcontainer.json
> +		"source=/home/${localEnv:USER}/.ssh,target=/app/.ssh,type=bind,consistency=cached"
@ilyasoifer has removed it - probably because he doesn't have /data
since he's the main consumer of this dev container I think we can leave it without that mount

2025-02-05 10:27 UTC, avigailmo commented on src/comparison/README.comparison.md
I'll leave that for @ilyasoifer

2025-02-05 10:31 UTC, avigailmo commented on src/filtering/Dockerfile
this will enforce us to build the comparison docker before the filtering docker. for now we run it as matrix in the GitHub action. I don't want to get into this now.
We can consider more base dockers in the future.

2025-02-05 10:32 UTC, avigailmo commented on src/filtering/README.filtering.md
> +This module includes filtering python scripts and utils for bioinformatics pipelines.
@ilyasoifer Can you please enrich the description of this member?

2025-02-05 10:33 UTC, avigailmo commented on src/filtering/ugbio_filtering/sec/allele_counter.py
@ilyasoifer what is sec?

2025-02-05 11:30 UTC, avigailmo commented on src/comparison/ugbio_comparison/vcf_pipeline_utils.py
> +def _fix_errors(df: pd.DataFrame) -> pd.DataFrame:
why? this is an internal function?

2025-02-05 13:00 UTC, avigailmo commented on src/filtering/pyproject.toml
> +    "xgboost==2.1.2",
yes

2025-02-09 06:53 UTC, ilyasoifer commented on src/filtering/ugbio_filtering/sec/allele_counter.py
A tool to remove locations based on the blacklist. @doron-st - has more details

2025-02-09 06:55 UTC, ilyasoifer commented on .devcontainer/filtering/devcontainer.json
> +		"source=/home/${localEnv:USER}/.ssh,target=/app/.ssh,type=bind,consistency=cached"
That is correct.

2025-02-09 09:05 UTC, inbalzelig-ugi approved these changes

2025-02-09 09:23 UTC, avigailmo commented
I've created a Jira for the documentation: 
https://ultimagen.atlassian.net/browse/BIOIN-2028

2025-02-09 09:23 UTC, merged